name: 'HHU_Auto_Checkin'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '28 14 * * 2,4'

jobs:
  auto_renew:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2

      - name: 'Set python'
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'

      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade selenium
      - name: 'Auto_Checkin'
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python main.py